### PR TITLE
Zha

### PR DESCRIPTION
**Pull request by dmulcahey**
Hello, I took a crack at correcting the last 2 issues that balloob references in your pull request to home-assistant. I am running this locally and it appears to correct the JSON serialization issue. Sorry if the code is a mess, I'm completely green when it comes to python. The multiple declarations of DATA_ZHA_DICT still need to be cleaned up but I wanted to bring the main part of the change to your attention to see what you thought. I am not getting serialization errors any more and my logbook and history are working again and all of my sensors still work :). Take a look and let me know what you think.

### CODE REVIEW

**Comment by rcloran** [comment]
Thanks @dmulcahey!

As you mentioned, there's no good way for you to contribute to the main PR, so this seems like a reasonable way of communicating your desired changes.

There are some changes to your PR that I'd like to make. I've got a couple hours to work on this now, so I'll update my main branch with your changes piecemeal.

Thanks again

**Comment by dmulcahey** [comment]
No problem, I have a few tracebacks I can send you too... I was able to get the iris motion sensor I have to work with a new battery :) but the presence sensor that I have appears to cause a timeout when I attempt to pair it to the network. I also have a couple that seem like there may be a constant mismatch somewhere. I can see if I can remote to my house to get them... want me to put them here? or is there an email address I can send them to?

**Comment by rcloran** [comment]
I think I've merged or re-implemented everything in this PR in my zha branch - please let me know if you run into any problems.

**Comment by dmulcahey** [comment]
I had a couple of previously removed devices reappear as joined sensors. Is there a way to remove them? 

David F. Mulcahey

**Comment by rcloran** [comment]
How did you remove them?

I don't think I've implemented any convenience ways of removing devices yet - you should be able to use the sqlite3 commandline tool to manually edit the database, though. 

```
$ sqlite3 .config/bellows/app.db
SQLite version 3.11.0 2016-02-15 17:29:24
Enter ".help" for usage hints.
sqlite> .tables
attributes  clusters    devices     endpoints
sqlite> delete from attributes where ieee='deviceieeeaddress';
sqlite> delete from clusters where ieee='deviceieeeaddress';
sqlite> delete from devices where ieee='deviceieeeaddress';
sqlite> delete from endpoints where ieee='deviceieeeaddress';
```

**Comment by dmulcahey** [comment]
I just ran the unpairing function on the devices themselves. 

David F. Mulcahey

**Pull request closed without merging**
